version: "3.1"

services:
  web:
    container_name: yoursite-web
    build: ./docker
    ports:
      - "8000:80"
      - "444:443"
    privileged: true
    volumes:
      - ./:/var/www/html
      - ./docker/apache/logs:/var/log/apache2
      - ./docker/apache/ssl:/etc/apache2/conf/ssl

  db:
    image: mysql:latest
    container_name: yoursite-db-host
    environment:
      MYSQL_ROOT_PASSWORD: yourRootPassword
      MYSQL_DATABASE: yourDatabase
      MYSQL_USER: yourUser
      MYSQL_PASSWORD: yourPassword
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d

  redis:
    image: "redis:latest"
    container_name: yoursite-redis-host
    volumes:
      - "./docker/redis/data:/data"
    command: redis-server --requirepass yourPassword
    ports:
      - "6379:6379"

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOSTS=yoursite-db-host
  #     - PMA_USER=root
  #     - PMA_PASSWORD=yourRootPassword
  #   ports:
  #     - 8080:80
