name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test the docker-compose Build process
      run: |
        docker-compose build
        docker-compose up --abort-on-container-exit
      working-directory: ./
